package view;

import controller.ControladorJuego;
import java.awt.Color;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {

    private ControladorJuego controlador;
    
    public MenuPrincipal() {
        initComponents();
        //inicilizar los colores por defecto
        btnSalir.setBackground(new Color(220, 220, 220));
        btnSalir.setForeground(Color.BLACK);
        btnSalir.setFocusPainted(false);
        btnFacil.setBackground(new Color(144, 238, 144));
        btnFacil.setForeground(Color.BLACK);
        btnFacil.setFocusPainted(false);
        btnIntermedio.setBackground(new Color(255, 218, 185));
        btnIntermedio.setForeground(Color.BLACK);
        btnIntermedio.setFocusPainted(false);
        btnDificil.setBackground(new Color(255, 50, 50));
        btnDificil.setForeground(Color.BLACK);
        btnDificil.setFocusPainted(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        controlador = new ControladorJuego();
        //jLabel3.setIcon(new javax.swing.ImageIcon("images/trivia.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFacil = new javax.swing.JToggleButton();
        btnDificil = new javax.swing.JToggleButton();
        btnIntermedio = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 358));
        setPreferredSize(new java.awt.Dimension(600, 358));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JUEGO DE TRIVIA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 40, 314, 42);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecciona el nivel de dificultad:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 90, 242, 19);

        btnFacil.setBackground(new java.awt.Color(144, 238, 144));
        btnFacil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnFacil.setForeground(new java.awt.Color(255, 255, 255));
        btnFacil.setText("FÁCIL");
        btnFacil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFacilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFacilMouseExited(evt);
            }
        });
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        jPanel1.add(btnFacil);
        btnFacil.setBounds(170, 120, 170, 40);

        btnDificil.setBackground(new java.awt.Color(244, 99, 81));
        btnDificil.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDificil.setForeground(new java.awt.Color(255, 255, 255));
        btnDificil.setText("DIFÍCIL");
        btnDificil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDificilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDificilMouseExited(evt);
            }
        });
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        jPanel1.add(btnDificil);
        btnDificil.setBounds(260, 170, 170, 40);

        btnIntermedio.setBackground(new java.awt.Color(255, 152, 0));
        btnIntermedio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        btnIntermedio.setText("INTERMEDIO");
        btnIntermedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIntermedioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIntermedioMouseExited(evt);
            }
        });
        btnIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntermedioActionPerformed(evt);
            }
        });
        jPanel1.add(btnIntermedio);
        btnIntermedio.setBounds(370, 120, 160, 40);

        btnSalir.setBackground(new java.awt.Color(220, 220, 220));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(260, 240, 170, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trivia.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 612, 330);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        String nombreJugador = solicitarNombreJugador();
        if (nombreJugador != null && !nombreJugador.trim().isEmpty()) {
            controlador.iniciarJuego("FACIL", nombreJugador);
            this.dispose();
        }
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntermedioActionPerformed
        String nombreJugador = solicitarNombreJugador();
        if (nombreJugador != null && !nombreJugador.trim().isEmpty()) {
            controlador.iniciarJuego("INTERMEDIO", nombreJugador);
            this.dispose();
        }
    }//GEN-LAST:event_btnIntermedioActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        String nombreJugador = solicitarNombreJugador();
        if (nombreJugador != null && !nombreJugador.trim().isEmpty()) {
            controlador.iniciarJuego("DIFICIL", nombreJugador);
            this.dispose();
        }
    }//GEN-LAST:event_btnDificilActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que quieres salir?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed
    //aqui comienzas el color a los botones
    private void btnFacilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacilMouseExited
        btnFacil.setBackground(new Color(144, 238, 144)); // Color original (azul claro)
        btnFacil.setForeground(Color.BLACK);
        //btnFacil.setFont();
    }//GEN-LAST:event_btnFacilMouseExited

    private void btnIntermedioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIntermedioMouseExited
        btnIntermedio.setBackground(new Color(255, 218, 185)); // Color original (naranja claro)
        btnIntermedio.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnIntermedioMouseExited

    private void btnFacilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacilMouseEntered
        btnFacil.setBackground(new Color(34, 139, 34));// Color al pasar el mouse (verde claro)
        btnFacil.setForeground(Color.WHITE); // Cambia color del texto si es necesario
    }//GEN-LAST:event_btnFacilMouseEntered

    private void btnIntermedioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIntermedioMouseEntered
        btnIntermedio.setBackground(new Color(255, 152, 0));// Color al pasar el mouse (rojo claro)
        btnIntermedio.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnIntermedioMouseEntered

    private void btnDificilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDificilMouseEntered
        btnDificil.setBackground(new Color(128, 0, 0));// Color al pasar el mouse (rojo claro)
        btnDificil.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnDificilMouseEntered

    private void btnDificilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDificilMouseExited
        btnDificil.setBackground(new Color(255, 50, 50)); // Color original (naranja claro)
        btnDificil.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnDificilMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setBackground(new Color(128, 128, 128)); // Color original (naranja claro)
        btnSalir.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setBackground(new Color(220, 220, 220)); // Color original (naranja claro)
        btnSalir.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnSalirMouseExited
    private String solicitarNombreJugador() {
        String nombre = JOptionPane.showInputDialog(
                this,
                "Ingresa tu nombre:",
                "Nombre del Jugador",
                JOptionPane.QUESTION_MESSAGE
        );
        return nombre;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDificil;
    private javax.swing.JToggleButton btnFacil;
    private javax.swing.JToggleButton btnIntermedio;
    private javax.swing.JToggleButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
